spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sopt?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: wodus050&

  config:
    activate:
      on-profile: dev

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create

    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: always

aws-property:
  access-key: AKIAV5DFWC62V2BBIA6G
  secret-key: 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
  aws-region: ap-northeast-2
  s3-bucket-name: do-sopt-server-demo-bucketjp

jwt:
  secret: jangchungdongwangjokbalbossammalwang